### ISSUE TITLE
KeyError: 'transl_table' when writing genbank output

### ISSUE THREAD

**Issue by btemperton** [gbouras13/phold#31] opened 2024-03-20 08:48 UTC
* phold version: 0.1.3
* Python version: Python 3.10.13
* Operating System: Ubuntu 18.04.6 LTS

### Description

Ran `pharokka` to annotate the genome, then ran `phold` on the resulting genbank file to annotate. `phold` runs fine and creates the files in the output file (e.g. `foldseek_results.tsv`, but fails when trying to write the genbank file.

### What I Did

```
mamba create -n pholdENV -c conda-forge -c bioconda phold
mamba activate pholdENV
phold install
#all ran fine


phold run -i genomes/CPL00056.fna.gbk  -o phold/CPL00056 -t 8

2024-03-20 08:39:17.464 | INFO     | phold.results.topfunction:get_topfunctions:35 - Processing Foldseek output
Traceback (most recent call last):
  File "/home/ben/mambaforge/envs/pholdENV/bin/phold", line 10, in <module>
    sys.exit(main())
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/phold/__init__.py", line 1356, in main
    main_cli()
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/phold/__init__.py", line 304, in run
    subcommand_compare(
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/phold/subcommands/compare.py", line 383, in subcommand_compare
    per_cds_df = write_genbank(
  File "/home/ben/mambaforge/envs/pholdENV/lib/python3.10/site-packages/phold/io/handle_genbank.py", line 244, in write_genbank
    transl_table = cds_feature.qualifiers["transl_table"][0]
KeyError: 'transl_table'
```
[CPL00056.fna.gbk.zip](https://github.com/gbouras13/phold/files/14663842/CPL00056.fna.gbk.zip)

**Comment by gbouras13** [comment] 2024-03-20 09:34
Hi @btemperton ,

I think the issue is that the Pharokka output must be from an earlier version (I see the GBK is dated Nov 30) and therefore lacks the 'transl_table' field. 

So if you re-run it with a latter version of Pharokka first e.g. v1.7 there should be no problems.

I do claim you can update your existing pharokka annotations (and want to support that), so nonetheless I'll certainly put in a fix for this issue.

Thanks for spotting it.

George

**Comment by gbouras13** [comment] 2024-03-20 09:52
@btemperton 

I've put in a fix - in the dev branch for now (I will make a release after testing etc).

If you are keen to try it out before release, this source install should work:

```
mamba create -n pholdENV2 -c conda-forge -c bioconda foldseek pip
mamba activate pholdENV2
git clone https://github.com/gbouras13/phold.git
cd phold
git pull origin dev
pip install -e .
```

George

**Closed** 2024-03-26 00:28 UTC
